services:
  database:
    container_name: postgresdb
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    image: postgres
    volumes:
      - type: bind
        source: ./database_scripts
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: volume
        source: postgresdbdata
        target: /var/lib/postgresql/data

  backend:
    build: .
    container_name: nodeback
    depends_on:
      - database
    links:
      - "database:postgresdatabase"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src

volumes:
  postgresdbdata:
